# Generated by Django 6.0.5 on 2026-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DNAResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=500)),
                ('count_a', models.IntegerField()),
                ('count_t', models.IntegerField()),
                ('count_c', models.IntegerField()),
                ('count_g', models.IntegerField()),
                ('is_valid', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
